"""Agave, rum and tequila items.

- agave_pup: a baby agave, a small blue-green rosette of pointed leaves on a clod of sandy root.
- agave_heart: the piña, an agave cut down in flower: a big pale yellow-green heart covered in the cut bases of its
  leaves (blue-green stubs in a diamond pattern), like a giant pineapple.
- roasted_agave: the same heart roasted in the kiln: caramel brown, the stubs darker, a syrupy shine.
- agave_fiber: a bundle of pale, coarse fiber tied at the middle with a twist of itself.
- molasses: a round glass flask full of near-black molasses, corked, a dark drip down its shoulder.
- agave_syrup: a slim bottle of clear golden agave syrup with a cork.
"""
from texturegen.compose import recolor
from texturegen.palettes import AGAVE, CORN, GLASS, MALT_AMBER, MALT_BLACK, PEAR, STRAW, WOOD_OAK

# 0-5 agave; a-e heart flesh (pear yellow-green); f-k roasted (malt amber); l-p fiber (straw); q r s t molasses;
# u v w x syrup (corn gold); G E glass glint and edge; K C cork; S sandy root
LEGEND = {
    **{str(i): AGAVE[i] for i in range(6)},
    **dict(zip("abcde", PEAR[1:6])),
    **dict(zip("fghijk", MALT_AMBER)),
    **dict(zip("lmnop", STRAW[1:6])),
    **dict(zip("qrst", MALT_BLACK[0:4])),
    **dict(zip("uvwx", CORN[2:6])),
    "E": GLASS[0], "G": GLASS[3],
    "K": WOOD_OAK[3], "C": WOOD_OAK[4],
    "S": STRAW[2],
}

AGAVE_PUP = """
................
................
................
................
.......4........
.......43.......
...4...43...4...
...43..43..43...
....43.43.43....
.4..3434343..4..
.43..343332.32..
..334343332331..
...2343433321...
....22322221....
.....SSmmSS.....
......SSSS......
"""

AGAVE_HEART = """
................
................
.....3..3..3....
....232.32.32...
....dcd3dc3dc...
...dcbcdcbdcbc..
...c3bc3bc3bc2..
..dcd2dcdcdcb2..
..cbc3bcbcbcb1..
..c3bcb3cbc3b1..
..dcbcdcbcbcb1..
...cb3bcb3cb1...
...bcbcbcbcb1...
....bbabbaba....
.....aaaaaa.....
................
"""

# The same heart, roasted: flesh to caramel, leaf stubs to dark brown.
ROASTED_AGAVE = recolor(AGAVE_HEART, {"e": "k", "d": "k", "c": "j", "b": "i", "a": "g", "3": "h", "2": "g", "1": "f"})

AGAVE_FIBER = """
................
................
...........po...
..........pon...
.........pon....
........ponm....
...op..ponm.....
...pon.onm......
....nomnoml.....
.....nmlmnm.....
......mlnomo....
.....mlm..nop...
....mlm....op...
...lml..........
..lml...........
................
"""

MOLASSES = """
................
.......CK.......
.......KK.......
......EGGE......
.......Et.......
......EttE......
.....EGttsrE....
....EGtssrrrE...
...EGtssrrrrqE..
...EGssrrrrqqE..
...EGsrrrrqqqE..
...EGsrrrqqqqE..
....Esrrqqqqq...
.....Erqqqqq....
......EEEEEE....
................
"""

AGAVE_SYRUP = """
................
.......CK.......
.......KK.......
......EEEE......
......EGxE......
......EGxE......
.....EEGxwEE....
.....EGxwwvE....
.....EGxwvvE....
.....EGwwvvE....
.....EGwvvuE....
.....EwwvvuE....
.....EwvvuuE....
.....EvvuuuE....
......EEEEE.....
................
"""

TEXTURES = {
    "agave_pup": AGAVE_PUP,
    "agave_heart": AGAVE_HEART,
    "roasted_agave": ROASTED_AGAVE,
    "agave_fiber": AGAVE_FIBER,
    "molasses": MOLASSES,
    "agave_syrup": AGAVE_SYRUP,
}

COMPARE = ["item/sweet_berries", "item/honey_bottle", "item/string"]
