"""Anise (item): a flat, creamy seed head on its stem, with a feathery leaf.

The broad umbrella of flowers going to seed on top, the stem running down to the bottom-left.
"""
from texturegen.palettes import FOLIAGE_FRESH, OAT

LEGEND = {**dict(zip("qwerty", FOLIAGE_FRESH)), **{str(i): OAT[i] for i in range(6)}}

GRID = """
................
.....45454......
....5453545.....
.....3e3e3......
.......e........
.......e..y.....
.......e.yty....
.......e..t.....
.......ee.e.....
........e.e.....
.......e.e......
......e.........
.....e..........
....e...........
................
................
"""

COMPARE = ["item/kelp", "item/fern"]
