"""Barley seeds: plump golden grains, each a tilted oval with a dark crease.

Distinct from vanilla wheat seeds (small green flecks) and beetroot seeds (flat tan).
"""
from texturegen.palettes import BARLEY

LEGEND = {str(i): BARLEY[i] for i in range(7)}

GRID = """
................
................
..........5.....
.........564....
.....5...542....
....564..32.....
....542.........
....32.....5....
..........564...
...5......542...
..564.....32....
..542...........
..32.....5......
.........564....
.........542....
.........32.....
"""

COMPARE = ["item/wheat_seeds", "item/beetroot_seeds", "item/pumpkin_seeds", "item/melon_seeds"]
