"""Brewhouse items: spent grain, sourdough starter, ale yeast.

- Spent grain: the grist heap after mashing, now damp and dull brown (same shape as grist,
  so the family reads: grist in, spent grain out).
- Sourdough starter: a squat stoneware crock with bubbly dough rising over the rim.
- Ale yeast: a small corked glass vial of creamy yeast slurry.
"""
import importlib.util
from pathlib import Path

from texturegen.palettes import CLAY, FLOUR, GLASS, ROOT, WOOD_OAK

_spec = importlib.util.spec_from_file_location("_malts", Path(__file__).with_name("malts.py"))
_malts = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(_malts)

# r0-5: ROOT (spent grain), K-P: CLAY, 0-5 digits unused here, w-z + v: FLOUR, g-j: GLASS, a-f: WOOD
LEGEND = {
    **dict(zip("ghjk", GLASS)),
    **dict(zip("KLMNOP", CLAY)),
    **dict(zip("tuvwxy", FLOUR)),
    **dict(zip("abcdef", WOOD_OAK)),
    **dict(zip("ABCDEF", ROOT)),
}

SPENT_GRAIN = _malts.recolor(_malts.GRIST, "AABCDE")

# A squat, straight-sided crock: widest at the flared rim, flat-bottomed, with a raised ridge.
# (The flour sack is the opposite: bulging middle, pinched neck, round bottom, so the two
# read apart even in grayscale.) Bubbly dough domes over the rim and drips down the left.
SOURDOUGH_STARTER = """
................
................
......wxxw......
....wxyyyxxw....
...wxyuxyyxuw...
..vwxyxxxxxwwv..
..KOxxOONNNMLK..
...KxwLLLLLLK...
...KNwNNNMMLK...
...KONNNNMMLK...
...KPOOOONNMK...
...KLLLLLLLKK...
...KONNNNMMLK...
...KNMMMMLLKK...
....KKKKKKKK....
................
"""

ALE_YEAST = """
................
.......dc.......
......dedc......
......ccbb......
......gkkg......
......gjjg......
.....gj..jg.....
....gj....jg....
....gvwwwvg.....
....gwxyxwgh....
....gwxxxwgh....
....gvwxwvgh....
....gvvwvvgh....
.....ghhhhg.....
................
................
"""

TEXTURES = {
    "spent_grain": SPENT_GRAIN,
    "sourdough_starter": SOURDOUGH_STARTER,
    "ale_yeast": ALE_YEAST,
}

COMPARE = ["item/honey_bottle", "item/potion", "item/flower_pot"]
