"""Cabbage (item): a round, pale blue-green head of leaves.

A ball outlined in dark green, lit top-left, with curving leaf edges across it.
"""
from texturegen.palettes import FOLIAGE_CABBAGE

LEGEND = dict(zip("qwerty", FOLIAGE_CABBAGE))

GRID = """
................
................
.....eeeeee.....
....eyyytyte....
...eyytyyttre...
..eytyyeytttre..
..eyyeyyyttrre..
..ettyeytttrre..
..erttetttrree..
..eetttyttrree..
...errttttree...
....eerrrree....
......eeee......
................
................
................
"""

COMPARE = ["item/melon_slice", "item/beetroot"]
