"""Cellar items: glass beer mug (empty + liquid and foam layers), tap, hydrometer.

The filled mug is three layers: the glass mug (layer 0), a grey liquid mask tinted in game by
the drink's color (layer 1), and a creamy foam head (layer 2). One texture set serves every beer,
and the colors keep pale ale, amber ale and stout distinct at a glance.
"""
from texturegen.palettes import FLOUR, GLASS, IRON, LIQUID, WOOD_OAK

LEGEND = {
    **dict(zip("ghjk", GLASS)),
    **{str(i): LIQUID[i] for i in range(6)},
    **dict(zip("uvwxyz", FLOUR)),
    **dict(zip("abcdef", WOOD_OAK)),
    **dict(zip("ABCDEF", IRON)),
}

MUG = """
................
................
................
...gjjjjjjjg....
...gk......g....
...gk......gggg.
...gk......g..g.
...gj......g..g.
...gj......g..g.
...gj......g..g.
...gj......gggg.
...gj......g....
...gj......g....
...ghhhhhhhg....
....gggggggg....
................
"""

MUG_LIQUID = """
................
................
................
................
................
....44443333....
....34333332....
....33333322....
....33333222....
....33332222....
....33322222....
....33222221....
....32222211....
................
................
................
"""

MUG_FOAM = """
................
................
...xyzzzyxw.....
..xyzzzzyyxw....
...xwwxwwxw.....
....w.w..w......
................
................
................
................
................
................
................
................
................
................
"""

TAP = """
................
................
................
................
.........ED.....
.........DC.....
.........CB.....
....cdddeecb....
...cddeeeedcb...
..bcccccccccb...
...bbbbbbbbba...
.........aa.....
.........ba.....
..........a.....
................
................
"""

HYDROMETER = """
................
..........jg....
.........jkg....
.........kg.....
........jkg.....
........Ckg.....
.......jkg......
.......Ckg......
......jkg.......
......Ckg.......
.....jDEg.......
....jDEEBg......
....gCDDBg......
....gBCCAg......
.....gggg.......
................
"""

TEXTURES = {
    "mug": MUG,
    "mug_liquid": MUG_LIQUID,
    "mug_foam": MUG_FOAM,
    "tap": TAP,
    "hydrometer": HYDROMETER,
}

COMPARE = ["item/glass_bottle", "item/honey_bottle", "item/spyglass"]
