"""Coriander (item): a sprig of fresh, round-lobed leaves.

Three little fans of leaves on thin stems joining at the bottom-left, bright fresh green.
"""
from texturegen.palettes import FOLIAGE_FRESH

LEGEND = dict(zip("qwerty", FOLIAGE_FRESH))

GRID = """
......y.y.......
.....ytyty......
......tyt.y.y...
.......e.ytyty..
..y.y..e..tyt...
.ytyty.e...e....
..tyt..e..e.....
...e...e.e......
....e..ee.......
.....e.e........
......ee........
......e.........
.....e..........
....e...........
................
................
"""

COMPARE = ["item/kelp", "item/fern"]
