"""Distillery items.

- spirit_bottle: the empty Spirit Bottle: a squat, square clear-glass decanter with flat shoulders, a short neck and a
  wooden-capped stopper; a glint runs down its left side.
- spirit_bottle_full (layer 0) + spirit_bottle_spirit (layer 1, grey, tinted per spirit in game): the same bottle, the
  spirit filling the glass above and below a label across its middle, so whiskey, rum and vodka read apart. The label is
  two more grey layers the game tints with the spirit's BottleLook colors, so clear spirits read apart too:
  spirit_bottle_label (layer 2: the paper, its ends shaded) and spirit_bottle_print (layer 3: a band of print across it).
  No two layers share a pixel.
- gin_basket: a little copper drum of fine mesh with banded rims and a handle, sprigs of juniper showing through.
- pot_still: the Pot Still's icon: a copper pot on its iron ring, the neck and head on top, and the swan neck curving over
  and down into the little glass spirit safe.
"""
from texturegen.palettes import COPPER, FLOUR, CLOTH, GLASS, IRON, LIQUID, WOOD_OAK

# e h j i: clear glass (edge, light, pale, glint); 1-5 the stopper's wood; 6-9 tinted greys (layer 1);
# p P Q: label edge, paper, print; k l m n o s: copper dark to light; A B C: iron; t u v: label greys (layers 2, 3)
LEGEND = {
    "e": GLASS[0], "h": GLASS[1], "j": GLASS[2], "i": GLASS[3],
    **{str(i): WOOD_OAK[i] for i in range(1, 6)},
    **dict(zip("6789", LIQUID[0:4])),
    "p": CLOTH[4], "P": FLOUR[4], "Q": FLOUR[2],
    **dict(zip("klmnos", COPPER)),
    "A": IRON[1], "B": IRON[2], "C": IRON[3],
    "t": LIQUID[1], "u": LIQUID[3], "v": LIQUID[5],
}

SPIRIT_BOTTLE = """
................
......2443......
.......32.......
......eiie......
......e..e......
...eeeh..heee...
...ei.......e...
...ei.......e...
...ei.......e...
...ei.......e...
...ei.......e...
...ei.......e...
...ej.......e...
...eeeeeeeeee...
................
................
"""

SPIRIT_BOTTLE_FULL = """
................
......2443......
.......32.......
......eiie......
......e..e......
...eeeh..heee...
...ei.......e...
...ei.......e...
................
................
................
...ei.......e...
...ej.......e...
...eeeeeeeeee...
................
................
"""

# The label's paper (tinted with the spirit's paper color): shaded at its ends, lit along its top.
SPIRIT_BOTTLE_LABEL = """
................
................
................
................
................
................
................
................
...tvvvvvvvvt...
...tu......ut...
...tuuuuuuuut...
................
................
................
................
................
"""

# Its print (tinted with the spirit's accent color): a band across the middle of the label.
SPIRIT_BOTTLE_PRINT = """
................
................
................
................
................
................
................
................
................
.....vvvvvv.....
................
................
................
................
................
................
"""

# The spirit in the glass, above and below the label (greys, tinted in game): lit at the top left, deeper low right.
SPIRIT_BOTTLE_SPIRIT = """
................
................
................
................
................
................
.....9999999....
.....9888887....
................
................
................
.....8877776....
.....8777666....
................
................
................
"""

POT_STILL = """
................
.....kkkk.......
....kosnmk......
....kosnmkkkkk..
.....knmlnnnnmk.
.....knmkkkkkmk.
....kosnmk...mk.
..kkosnnnmkk.mk.
.kosnnnnnnnmkmk.
.kosnnnnnnnmkhjk
.knsnnnnnnmmkiek
.knnnnnnnmmlkeek
..knnnnmmmlk.kk.
...kkllllkk.....
....ACCCCA......
................
"""

GIN_BASKET = """
................
................
.....kkkkkk.....
....k......k....
...kkkkkkkkkk...
...ksnosnosnk...
...kn.n.n.n.k...
...kosnosnosk...
...k.n.n.n.nk...
...knosnosnok...
...kn.n.n.n.k...
...ksnosnosnk...
...kllllllllk...
....kkkkkkkk....
................
................
"""

TEXTURES = {
    "gin_basket": GIN_BASKET,
    "spirit_bottle": SPIRIT_BOTTLE,
    "spirit_bottle_full": SPIRIT_BOTTLE_FULL,
    "spirit_bottle_label": SPIRIT_BOTTLE_LABEL,
    "spirit_bottle_print": SPIRIT_BOTTLE_PRINT,
    "spirit_bottle_spirit": SPIRIT_BOTTLE_SPIRIT,
    "pot_still": POT_STILL,
}

COMPARE = ["item/glass_bottle", "item/potion", "item/honey_bottle"]
