"""Drying Rack results.

- dried_chili: the fresh chili's curve, shrunk, darkened to maroon and creased, hung from a loop
  of twine where its green stem was: "a chili, dried" at a glance.
- jerky: a ragged, flat strip of dark dried meat (browner than raw or cooked beef) with pale
  streaks of fat and notched edges.
"""
from texturegen.palettes import FRUIT_RED, MALT_AMBER, ROOT

# 0-3 dark reds, s dried stem, t twine, j-m jerky browns, a fat streak
LEGEND = {
    **{str(i): FRUIT_RED[i] for i in range(4)},
    "s": ROOT[2],
    "t": ROOT[4],
    **dict(zip("jklm", [MALT_AMBER[0], FRUIT_RED[0], MALT_AMBER[1], FRUIT_RED[1]])),
    "a": MALT_AMBER[3],
}

DRIED_CHILI = """
................
..........tt....
.........t..t...
.........t..t...
..........tts...
.........ss.....
........3221....
.......32010....
......3221......
.....3201.......
.....321........
.....3201.......
......210.......
.......110......
........00......
................
"""

JERKY = """
................
................
............km..
..........kmmlk.
.........kmam lk
........kmlalk..
.......kmlmlk...
......kmalmk....
.....kmlmalk....
....kmlmlk......
...kmaml k......
..kmlmlk........
.kmmlk..........
.kkjj...........
................
................
""".replace(" ", "l")

TEXTURES = {"dried_chili": DRIED_CHILI, "jerky": JERKY}

COMPARE = ["item/dried_kelp", "item/cooked_beef", "item/rabbit_hide"]
