"""Dried hops: the same cone shape as fresh hop cones, now papery olive-tan and leafless.

Three cones in a loose cluster; ready for the brew kettle.
"""
from texturegen.palettes import HOP_DRIED

LEGEND = dict(zip("zxcvbn", HOP_DRIED))

GRID = """
................
................
................
......nb........
.....nbbv.......
.....bvvc.......
.....nbbv..nb...
.....bvvc.nbbv..
..nb.vccx.bvvc..
.nbbv.cx..nbbv..
.bvvc.....bvvc..
.nbbv.....vccx..
.bvvc......cx...
.vccx...........
..cx............
................
"""

COMPARE = ["item/wheat", "item/dried_kelp", "item/cocoa_beans"]
