"""Garden vegetables from the bushes, and their seeds.

- tomato: a round red tomato with a green star cap
- chili: a slim, curved red pepper on a green stem
- cucumber: a long dark-green cucumber with pale speckles
- tomato / chili / cucumber seeds: small flat pale seeds, scattered
- coffee beans: pale green, unroasted beans, each with its center crease
"""
from texturegen.compose import blank, stamp, to_grid
from texturegen.palettes import FOLIAGE_CROP, FOLIAGE_DUSTY, FOLIAGE_FRESH, FRUIT_RED, OAT

# 0-5 FRUIT_RED, q-y FOLIAGE_FRESH, m n o p s z OAT (seeds), A-F FOLIAGE_CROP (cucumber), g-l FOLIAGE_DUSTY (coffee)
LEGEND = {
    **{str(i): FRUIT_RED[i] for i in range(6)},
    **dict(zip("qwerty", FOLIAGE_FRESH)),
    **dict(zip("mnopsz", OAT)),
    **dict(zip("ABCDEF", FOLIAGE_CROP)),
    **dict(zip("ghijkl", FOLIAGE_DUSTY)),
}

TOMATO = """
................
................
.......t.t......
......tyrty.....
....44trtr33....
...4554tr4332...
..455444433321..
..454444333221..
..444433332221..
..344333332211..
..333333322211..
...3332222211...
....22222111....
......1111......
................
................
"""

# Curved like a crescent, with a curled stem: a straight red diagonal would read as a carrot.
CHILI = """
................
...........rr...
..........r.y...
.........tyt....
........35532...
.......35521....
......3552......
.....3531.......
.....352........
.....3521.......
......321.......
.......221......
........11......
.........1......
................
................
"""

CUCUMBER = """
................
................
............FE..
...........FEDC.
..........FEFDC.
.........EFEDC..
........FEFDC...
.......EFEDC....
......FEFDC.....
.....EFEDC......
....FEFDC.......
...EFEDC........
..EEDCC.........
..DCC...........
................
................
"""

SEED = """
ps
op
"""

BEAN = """
.jk.
jkhj
kihj
jhij
.ii.
"""


def scatter(sprite, spots):
    c = blank()
    for x, y in spots:
        stamp(c, sprite, x, y)
    return to_grid(c)


SEED_SPOTS = ((10, 2), (4, 3), (11, 6), (7, 7), (2, 8), (12, 11), (6, 11), (9, 13))

TEXTURES = {
    "tomato": TOMATO,
    "chili": CHILI,
    "cucumber": CUCUMBER,
    "tomato_seeds": scatter(SEED, SEED_SPOTS),
    "chili_seeds": scatter("sp\npo", SEED_SPOTS[1:]),
    "cucumber_seeds": scatter("ss\npp\nop", SEED_SPOTS[:6]),
    "coffee_beans": scatter(BEAN, ((8, 2), (3, 4), (10, 7), (5, 9))),
}

COMPARE = ["item/apple", "item/carrot", "item/beetroot_seeds", "item/cocoa_beans"]
