"""Herb items (also what you plant): a sprig or bunch of each.

- mint: a sprig of paired, rounded bright-green leaves
- lavender: a small bunch of stems with purple flower heads, tied at the bottom
- wormwood: a sprig of finely cut, silvery grey-green leaves
"""
from texturegen.palettes import FLOUR, FOLIAGE_DUSTY, FOLIAGE_FRESH, LAVENDER, ROOT

# q-y FOLIAGE_FRESH, a b c d g h FOLIAGE_DUSTY, 0-5 LAVENDER, S/U FLOUR (silver), n ROOT (tie)
LEGEND = {
    **dict(zip("qwerty", FOLIAGE_FRESH)),
    **dict(zip("abcdgh", FOLIAGE_DUSTY)),
    **{str(i): LAVENDER[i] for i in range(6)},
    "S": FLOUR[3], "U": FLOUR[1], "n": ROOT[2],
}

MINT = """
................
..........yy....
.........ytty...
..........te....
......yy.e.yy...
.....ytty.ytty..
......tee..te...
..yy...e.ee.....
.ytty..ee.......
..tee.e.........
....ee..........
....e...........
...e............
..e.............
................
................
"""

LAVENDER_BUNCH = """
................
...........5....
.........5.4.5..
.......5.4.3.4..
.......4.3.2.3..
.......3.2.d.2..
.......2.d.d.d..
........d.dd.d..
.........dd.d...
.........ddd....
........nnd.....
.......dnn......
......dd........
.....d..........
................
................
"""

WORMWOOD = """
................
...........h.h..
..........hShS..
...........Sg...
.......h.hg.h...
......hShSg.Sh..
.......SghgSg...
...h.h..gg......
..hShSgg........
...Sg.g.........
....gg..........
....g...........
...g............
..g.............
................
................
"""

TEXTURES = {"mint": MINT, "lavender": LAVENDER_BUNCH, "wormwood": WORMWOOD}

COMPARE = ["item/kelp", "item/sweet_berries"]
