"""Hop cones: three papery pale-green cones on a sprig with one leaf.

Layered bracts are suggested by alternating light/dark rows, the way a hop
cone's scales overlap. Pale lime reads apart from every vanilla green.
"""
from texturegen.palettes import FOLIAGE_FRESH, HOP_CONE

LEGEND = {**dict(zip("asdfgh", FOLIAGE_FRESH)), **dict(zip("zxcvbn", HOP_CONE))}

GRID = """
................
...........gh...
..........fghg..
..........sdf...
.........d......
........d.......
...nb..d........
..nbbvd.........
..bvvc....nb....
..nbbv...nbbv...
..bvvc...bvvc...
..vccx...nbbv...
...cx....bvvc...
.........vccx...
..........cx....
................
"""

COMPARE = ["item/sweet_berries", "item/glow_berries", "item/kelp"]
