"""Hop rhizome: a knobby root cutting with pale buds and a green shoot - what you plant.

Diagonal from bottom-left to top-right like vanilla items.
"""
from texturegen.palettes import FOLIAGE_FRESH, ROOT

LEGEND = {**{str(i): ROOT[i] for i in range(6)}, **dict(zip("asdfgh", FOLIAGE_FRESH))}

GRID = """
................
................
............gh..
...........fg...
...........d....
.........345....
........3454....
.......24543....
......2345.5....
.....23452......
....1345........
...12354........
..1234..........
..123...........
...1............
................
"""

COMPARE = ["item/potato", "item/carrot", "item/beetroot_seeds"]
