"""Citrus peel (GDD section 17.4): zest for gin, bitters and spiced rum.

- lemon_peel: a curling spiral strip of bright yellow peel, the pale pith showing on its inner side.
- orange_peel: the same curl in deep orange.
"""
from texturegen.palettes import FLOUR, LEMON

# 1-5 peel (dark to bright); p pith
LEGEND = {**dict(zip("12345", LEMON[1:6])), "p": FLOUR[4]}

LEMON_PEEL = """
................
................
..........345...
.........34p5...
........34pp4...
.......34p.43...
......2345.32...
.....2345p.2....
....234p..32....
...234pp.32.....
...23p..321.....
....2p.321......
.....23321......
......221.......
................
................
"""

TEXTURES = {
    "lemon_peel": LEMON_PEEL,
}
