"""Rice (item): a small heap of rice grains (also what you plant).

Slim grains piled into a little mound, each grain a lit end over a shaded end, in warm
cream with a few golden husks (paddy rice) mixed in. A mound of distinct grains reads as
"rice" where the grists are smooth heaps of powder and the seeds are scattered.
"""
from texturegen.palettes import FLOUR, RICE

# 0-5 = FLOUR (cream grains, cool grey shadows), a-f = RICE (golden husks)
LEGEND = {**{str(i): FLOUR[i] for i in range(6)}, **dict(zip("abcdef", RICE))}

GRID = """
................
................
................
................
................
................
.......54.......
.....5423e5.....
....54e23542....
...5423542d23...
..54235e4235e2..
..4235423542321.
.54e2354e235422.
.2321232123213b.
..1c11111111b1..
................
"""

COMPARE = ["item/sugar", "item/wheat_seeds", "item/bone_meal"]
