"""Kitchen snacks:

- popcorn: white puffs (a few yellow hulls) heaped in a red-and-white striped paper bag.
- rice_ball: a pressed, rounded triangle of white rice with grain texture, wrapped at the bottom in a strip
  of dried kelp (its recipe needs one).
- jam_toast: a toasted slice (golden crust, pale crumb) with a glossy spread of dark berry jam.
"""
from texturegen.compose import sibling
from texturegen.palettes import BLACKBERRY, CORN, FLOUR, FOLIAGE_DUSTY, FRUIT_RED, MALT_AMBER, OAT

shapes = sibling(__file__, "_shapes")

# A-F flour whites; c corn hull; G-K crust; L-O crumb; P-R jam
LEGEND = {
    **dict(zip("ABCDEF", FLOUR)),
    "c": CORN[4],
    "d": CORN[3],
    **dict(zip("GHIJK", MALT_AMBER[0:5])),
    **dict(zip("LMNO", OAT[2:6])),
    **dict(zip("PQR", [BLACKBERRY[2], BLACKBERRY[3], BLACKBERRY[5]])),
    "S": FRUIT_RED[3],   # bag stripes: red and white
    "s": FLOUR[4],
    **dict(zip("nop", FOLIAGE_DUSTY[0:3])),   # the dried kelp wrap: near-black green with a sheen
}


# Popcorn heaped in a striped paper bag: the bag says "popcorn" at a glance, where a bare heap
# of white puffs read as a cookie.
POPCORN = """
................
......FE.EF.....
....FEEDFEEDF...
...EFEDcEFDEDE..
...DEcDEEDcEDC..
....DEEDCEDDC...
....sSSssSSss...
....sSSssSSss...
....sSSssSSss...
....sSSssSSss...
.....SSssSSs....
.....SSssSSs....
.....SSssSSs....
......SssSS.....
................
................
"""


RICE_BALL = """
................
................
................
.......BB.......
......BEEB......
.....BEFEEB.....
....BEFFEEDB....
....BEFEEEDB....
...BEEEEEEDDB...
...BEopooonDB...
..BDEopooonDCB..
..BDDoooonnDCB..
...BConnnnnCB...
....BnnnnnnB....
................
................
"""


def rice_ball() -> str:
    rows = [list(r) for r in RICE_BALL.strip("\n").splitlines()]
    for x, y in ((7, 6), (9, 8), (6, 10), (10, 11), (8, 9), (5, 9)):   # grains catching the light
        if rows[y][x] in "DE":
            rows[y][x] = "F" if rows[y][x] == "D" else "D"
    return "\n".join("".join(r) for r in rows)


# A sandwich-loaf slice (domed top over a straight base) so it reads as bread, not a framed
# picture; the jam is spread unevenly, with a glossy highlight and a drip toward the crust.
JAM_TOAST = """
................
................
....HHHHHHHH....
..HHJKKKKKKJHH..
.HJKNNNNNNNNNJH.
.HJNNQRRPPPNNJH.
.HJNPQRPPPPPNJH.
.HJJNPPPPPPPJJH.
..HJNPPPPPPPJH..
..HJMNPPPPPNJH..
..HJMNNPPPNNJH..
..HJMMNNPNNNJH..
..HJMMMNNNNMJH..
..HIJJJJJJJJIH..
...HHHHHHHHHH...
................
"""

TEXTURES = {
    "popcorn": POPCORN,
    "rice_ball": rice_ball(),
    "jam_toast": JAM_TOAST,
}

COMPARE = ["item/bread", "item/cookie", "item/sugar"]
