"""Straw: a bundle of dry stalks tied with twine, flared at both ends.

No grain heads (that's wheat or barley), just stalks: alternating light and dark columns show
the individual straws, and the dark twine band pinches the bundle in the middle.
"""
from texturegen.palettes import ROOT, STRAW

# 0-5 straw, t-u twine
LEGEND = {**{str(i): STRAW[i] for i in range(6)}, **dict(zip("tu", ROOT[0:2]))}

GRID = """
................
....4..5..5.4...
....34.45.4.3...
.....3454543....
.....3454543....
......34543.....
......34543.....
......tuuut.....
......tuuut.....
......34543.....
......34543.....
.....3454543....
.....3454543....
....3.45.54.3...
...2..3.4.3..2..
................
"""

COMPARE = ["item/wheat", "block/hay_block_side", "item/stick"]
