"""Sugar beet (item): a fat cream cone of a root with a tuft of leaf stalks on top.

Tapers from its broad, lit shoulder at the top-right down to a thin tail at the bottom-left.
Cream where vanilla's beetroot is red, and cone-shaped where it's round.
"""
from texturegen.palettes import FOLIAGE_CROP, SUGAR_BEET

LEGEND = {**{str(i): SUGAR_BEET[i] for i in range(6)}, **dict(zip("qwerty", FOLIAGE_CROP))}

GRID = """
................
..........y.yy..
.........yty.te.
..........tte...
.........yrr....
........55443...
.......554432...
......554433....
.....54443321...
.....44433221...
....4433221.....
...343321.......
...33221........
..321...........
.21.............
................
"""

COMPARE = ["item/beetroot", "item/carrot", "item/potato"]
