"""Winery vessels and wine yeast.

- wine_bottle: the empty dark-green bottle: long neck, sloping shoulders, a pale glint down the left.
- wine_bottle_full (layer 0) + wine_bottle_wine (layer 1, grey, tinted per drink in game): the same bottle,
  corked, with a paper label; the foil over the cork and neck and the wide band across the label take the
  wine's color, so a shelf of bottles reads apart without seeing through the dark glass.
- juice_bottle (layer 0) + juice_bottle_juice (layer 1, tinted per juice): a corked, round-bellied clear
  glass flask, the juice filling its belly. Juices go in vanilla's glass bottle; this is how a full one looks.
- wine_yeast: the ale-yeast vial (brewhouse_items.py) with a pale mauve slurry, from wine lees.
"""
from texturegen.compose import recolor, sibling
from texturegen.palettes import BOTTLE_GLASS, CLOTH, FLOUR, GLASS, LIQUID, SUGAR_BEET, WOOD_OAK

brewhouse = sibling(__file__, "brewhouse_items")

# o d m l g: bottle glass (outline, dark, mid, light, glint); c C cork; p P label; 0-3 tinted greys;
# 1g 3g clear glass (edge, glint) as "e" "i"; v w x y mauve yeast slurry; ghjk vial glass (ale yeast's letters)
LEGEND = {
    "o": BOTTLE_GLASS[0], "d": BOTTLE_GLASS[1], "m": BOTTLE_GLASS[2], "l": BOTTLE_GLASS[3], "G": BOTTLE_GLASS[5],
    "c": WOOD_OAK[3], "C": WOOD_OAK[4],
    "p": CLOTH[4], "P": FLOUR[4],
    **dict(zip("0123", LIQUID[0:4])),
    "e": GLASS[0], "i": GLASS[3],
    **dict(zip("ghjk", GLASS)),
    **dict(zip("qrabf", WOOD_OAK[1:6])),   # the vial's cork
    **dict(zip("tuvwxy", SUGAR_BEET)),
}

WINE_BOTTLE = """
................
.......oo.......
.......dm.......
.......dl.......
.......dl.......
.......dl.......
......odlo......
.....odmllo.....
.....odGmlo.....
.....odGmlo.....
.....odGmlo.....
.....odmmlo.....
.....odmmlo.....
.....odmmlo.....
.....oooooo.....
................
"""

WINE_BOTTLE_FULL = """
................
.......CC.......
.......cc.......
.......dl.......
.......dl.......
.......dl.......
......odlo......
.....odmllo.....
.....odGmlo.....
.....pPPPPp.....
.....pP..Pp.....
.....pP..Pp.....
.....pPPPPp.....
.....odmmlo.....
.....oooooo.....
................
"""

# Foil over the cork and neck (rows 1-4) and a two-row band across the label (rows 10-11), in greys to be tinted:
# big enough that a row of bottles reads apart by color.
WINE_BOTTLE_WINE = """
................
.......32.......
.......21.......
.......21.......
.......10.......
................
................
................
................
................
......3221......
......2110......
................
................
................
................
"""

JUICE_BOTTLE = """
................
.......Cc.......
.......cc.......
......eiee......
.......ee.......
......e..e......
.....e....e.....
....e......e....
...ei.......e...
...ei.......e...
...ei.......e...
...ei.......e...
....ei.....e....
.....eeeeeee....
................
................
"""

JUICE_BOTTLE_JUICE = """
................
................
................
................
................
................
................
.....333333.....
....33322222....
....3222211.....
....3222110.....
.....222110.....
.....111100.....
................
................
................
"""

TEXTURES = {
    "wine_bottle": WINE_BOTTLE,
    "wine_bottle_full": WINE_BOTTLE_FULL,
    "wine_bottle_wine": WINE_BOTTLE_WINE,
    "juice_bottle": JUICE_BOTTLE,
    "juice_bottle_juice": JUICE_BOTTLE_JUICE,
    # same vial: its cork letters moved onto ours, the slurry letters (t-y) mauve here
    "wine_yeast": recolor(brewhouse.ALE_YEAST, {"b": "q", "c": "r", "d": "a", "e": "b"}),
}

COMPARE = ["item/potion", "item/honey_bottle", "item/glass_bottle"]
