"""Courage effect icon (18x18): a horned iron helmet with a riveted copper band, standing firm."""
from texturegen.palettes import COPPER as C, IRON as I, STRAW as S

LEGEND = {
    "o": I[0], "1": I[1], "2": I[2], "3": I[3], "4": I[4], "5": I[5],
    "k": C[0], "D": C[2], "M": C[3], "L": C[4], "H": C[5],
    "s": S[0], "b": S[3], "B": S[5],
}

GRID = """
..................
..................
..................
..................
.s..............s.
sBs............sBs
sBbs...oooo...sbBs
sBbs.oo5443oo.sbBs
.sBbo55443322obBs.
.sBbo54433322obBs.
..sbo44333221obs..
...kLHLLLLLMMDk...
...kMkMMMMMMkDk...
...kkkkkkkkkkkk...
..................
..................
..................
..................
"""
