"""Tipsy effect icon (18x18): a glass mug of golden ale, foam spilling over, bubbles rising."""
from texturegen.palettes import FLOUR as F, GLASS as G, GOLD as A

LEGEND = {
    "g": G[0], "3": G[3],
    "x": A[1], "y": A[2], "z": A[4],
    "k": F[1], "c": F[2], "w": F[3], "W": F[5],
}

GRID = """
..................
.............kk...
............kWWk..
...kkk.kkk..kWWk..
..kWWWkWWWk..kk...
.kWWWWWWWWWk......
.kwWWWWWWWwk..k...
.gcwwcWwwcwg.kWk..
.g3yzwyyyyxgggkg..
.g3yyzyyyyxg..g...
.g3yyyyyyxxg..g...
.g3yyyyyyxxg..g...
.g3yyyyyyxxgggg...
.g3yyyyyxxxg......
.gxxxxxxxxxg......
..ggggggggg.......
..................
..................
"""
