"""Warmth effect icon (18x18, vanilla's effect size): a red knitted mitten with a cream ribbed cuff."""
from texturegen import palettes as P

R, F = P.FRUIT_RED, P.FLOUR
LEGEND = {
    "o": R[0], "d": R[1], "m": R[2], "r": R[3], "l": R[4], "h": R[5],
    "k": F[1], "c": F[2], "w": F[3], "W": F[5],
}

GRID = """
..................
.......ooooo......
......ohhlrro.....
.....ohllrrrmo....
.....ohlrrrrmo....
..oo.olrrrrrmo....
.oldoolrrrrrmo....
.olrdrlrrrrmmo....
.olrrrrrrrrmmo....
..olrrrrrrrmmo....
...omrrrrrmmdo....
....ommmmmmddo....
...kkkkkkkkkkkk...
...kWWwWWwWWwck...
...kWWwWWwWWwck...
...kwwcwwcwwcck...
...kkkkkkkkkkkk...
..................
"""
